### ISSUE TITLE
cannot set image_dialog_images_html

### ISSUE THREAD

**Issue by ccwalkerjm** [eissasoubhi/summernote-gallery#1]
I am using a cloud service.   How can I set image_dialog_images_html so that it works with a function.  I use Promise to make the function synchronous.

**Comment by eissasoubhi** [comment]
I'm not sure of what you want, do you want to set image_dialog_images_html inside a function? 
can you provide more details so I can understand your issue?

**Comment by rhafaman** [comment]
Hi,

I have problem: summernote-gallery-extension.js:131 Uncaught TypeError: Cannot read property 'length' of undefined

What can it be?

**Comment by eissasoubhi** [comment]
Hi @rhafaman 

it's nothing to worry about, the error comes from the function recoverEditorFocus() which is a workaround for a summernote bug, to insert the selected image (from image dialog) in the last cursor position in summernote editor.

the problem is fixed  :
https://github.com/eissasoubhi/summernote-gallery/commit/68ba699ec3c7545c29c1b12eb35da7303f45314b
