### ISSUE TITLE
Loading more images in modal

### ISSUE THREAD

**Issue by debarshi121** [eissasoubhi/summernote-gallery#4]
What if we have thousands of images in our gallery modal. Is there any possible solution on loading more images on modal scroll via ajax?

**Comment by eissasoubhi** [comment]
This feature has been added in the new version https://github.com/eissasoubhi/summernote-gallery/commit/3586ff0d9e0344496b521149b433dfe37ef1b6ea. 
see the demo http://eissasoubhi.github.io/summernote-gallery/

Thanks for the suggestion.

**Comment by ryumada** [comment]
> This feature has been added in the new version [3586ff0](https://github.com/eissasoubhi/summernote-gallery/commit/3586ff0d9e0344496b521149b433dfe37ef1b6ea).
> see the demo http://eissasoubhi.github.io/summernote-gallery/
> 
> Thanks for the suggestion.

Hi, I have an Issue with this feature, the modal won't load another ajax request, I have followed all your instruction but still not working on my project. I have looked at your demo too, but I think it doesn't explain how to use this.

My server is working just fine, It get the json data with `links.next` url on response and of course it has `?page=2`. If i visit the link using `?page=2` it will get `?page=3` parameter and so on. the problem is the plugin won't trigger another ajax request.

here is my summernote-gallery settings,
```
gallery: { // summernote gallery settings
  source: {
    // data: [],
    url: url_getIndex + 
      "?page=" + url_getNextPage + 
      "&path=" + path +
      "&index=" + index +
      "&url_getIndex=" + url_getIndex +
      "&url_getNextPage=" + url_getNextPage +
      "&url_path=" + url_path +
      "&path=" + path,
    // responseDataKey: 'data',
    nextPageKey: 'links.next',
  },
  modal: {
    loadOnScroll: true,
    // maxHeight: 300,
    title: "Tambahkan Gambar",
    close_text: 'Batalkan',
    ok_text: 'Tambahkan',
    selectAll_text: 'Pilih Semua',
    deselectAll_text: 'Pilih Tidak Semua',
    noImageSelected_msg: 'Tidak ada gambar yang dipilih, harap pilih satu',
  }
}
```

and here is for the json file generated by my server,
[gallery.txt](https://github.com/eissasoubhi/summernote-gallery/files/5936755/gallery.txt)

What's the problem? Is there something I missed?
